authoringtool/authoringtool/urls.py
from django.conf.urls import patterns, include, url
from registration.backends.simple.views import RegistrationView 
from django.contrib import admin
admin.autodiscover()

# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/sequencelistings/'


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sequencelistings/', include('sequencelistings.urls', namespace='sequencelistings')),
    url(r'^accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
#     url(r'^accounts/password/change', MyRegistrationView.as_view(), name='auth_password_change'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    
)

authoringtool/sequencelistings/urls.py
'''
Created on Apr 12, 2015

@author: ad
'''
from django.conf.urls import patterns, url

from sequencelistings import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add_sequencelisting/$', views.add_sequencelisting, name='add_sequencelisting'),
    url(r'^about/$', views.about, name='about'),
    url(r'^download/(?P<fileName>.*)/$', views.download, name='download'),
    url(r'^sl(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'^sl(?P<pk>\d+)/edit_sequence_data/$', views.edit_sequence_data, name='edit_sequence_data'),
#     inconsistent names url vs function add_seq vs add_sequence!!!!
    url(r'^sl(?P<pk>\d+)/add_seq/$', views.add_sequence, name='add_seq'),
    url(r'^sl(?P<pk>\d+)/add_title/$', views.add_title, name='add_title'),
    url(r'^sl(?P<pk>\d+)/seq(?P<spk>\d+)/$', views.sequence, name='sequence'),
    url(r'^sl(?P<pk>\d+)/seq(?P<spk>\d+)/add_feature/$', views.add_feature, name='add_feature'),
    url(r'^sl(?P<pk>\d+)/seq(?P<spk>\d+)/add_multiple_feature/$', views.add_multiple_feature, name='add_multiple_feature'),
    url(r'^sl(?P<pk>\d+)/seq(?P<spk>\d+)/f(?P<fpk>\d+)/add_qualifier/$', 
        views.add_qualifier, 
        name='add_qualifier'),
    url(r'^sl(?P<pk>\d+)/seq(?P<spk>\d+)/f(?P<fpk>\d+)/edit_feature/$', views.edit_feature, name='edit_feature'),
    
    url(r'^sl(?P<pk>\d+)/xmloutput/$', views.generateXml, name='xmloutput'),
    
    url(r'^restricted/$', views.restricted, name='restricted'),
    
)

authoringtool/sequencelistings/forms.py
'''
Created on Apr 11, 2015

@author: ad
'''

from django.forms import Form, ModelForm, CharField, ChoiceField, PasswordInput
from django.contrib.auth.models import User 
from models import SequenceListing, Title, Sequence, Feature, Qualifier 
import util

class SequenceListingForm(ModelForm):
#     filingDate = DateField()
    
    class Meta:
        model = SequenceListing
        fields = [
                  'fileName', 
                  'applicantFileReference',
                  'IPOfficeCode', 
                  'applicationNumberText', 
                  'filingDate', 
                  'earliestPriorityIPOfficeCode', 
                  'earliestPriorityApplicationNumberText', 
                  'earliestPriorityFilingDate', 
                  'applicantName', 
                  'applicantNameLanguageCode', 
                  'applicantNameLatin', 
                  'inventorName', 
                  'inventorNameLanguageCode', 
                  'inventorNameLatin', 
                  ]
        

class TitleForm(ModelForm):
    class Meta:
        model = Title
        fields = [
                'inventionTitle', 
                'inventionTitleLanguageCode'
                ] 
        
class SequenceForm(ModelForm):
    organism = CharField(label='Organism', max_length=200)

    class Meta:
        model = Sequence
        fields = [
#                   'sequenceListing', 
#                 'sequenceIdNo', 
#                   'length',
                  'moltype',
#                   'division',
#                   'otherSeqId',
                  'residues'] 

class FeatureForm(ModelForm):
    c = []
    def __init__(self, *args, **kwargs):
        moltype = kwargs.pop('mt')
        super(FeatureForm, self).__init__(*args, **kwargs)
        if moltype == 'AA':
            c = util.FEATURE_KEYS_PRT 
        else:
            c = util.FEATURE_KEYS_DNA
 
        self.fields['featureKey'] = ChoiceField(choices=c, label='Feature key')
         
    class Meta:
        model = Feature
        fields = ['featureKey', 'location']   


class EditFeatureForm(ModelForm):     
    class Meta:
        model = Feature
        fields = ['featureKey', 'location']   


class MultipleFeatureForm(Form):
    featureChoice = []
    qualifierChoice = []
    def __init__(self, *args, **kwargs):
        moltype = kwargs.pop('moltype')
        super(MultipleFeatureForm, self).__init__(*args, **kwargs)
        if moltype == 'AA':
            featureChoice = util.FEATURE_KEYS_PRT 
        else:
            featureChoice = util.FEATURE_KEYS_DNA

        self.fields['featureKey'] = ChoiceField(choices=featureChoice, label='Feature key')
        self.fields['location'] = CharField(max_length=100, label='Location')
        self.fields['qualifierName'] = CharField(max_length=100, label='Qualifier name')
        self.fields['qualifierValue'] = CharField(max_length=100, label='Qualifier value')
        
        
class QualifierForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        c=[]
        feature = kwargs.pop('feature')
        fk = feature.featureKey
        super(QualifierForm, self).__init__(*args, **kwargs)
        if fk in util.QUALIFIER_CHOICE.keys():
            c = util.QUALIFIER_CHOICE.get(fk)
        
        if c:
            self.fields['qualifierName'] = ChoiceField(choices=c, label='Qualifier name') 
        else:
            self.fields['qualifierName'] = CharField(max_length=100, label='Qualifier name')
            
        self.fields.keyOrder = ['qualifierName', 'qualifierValue']  

    class Meta:
        model = Qualifier
        fields = [
                'qualifierName', 
                  'qualifierValue']


class UserForm(ModelForm):
    password = CharField(widget=PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class FormulaForm(Form):
    reg1 = CharField(label='region1', max_length=500)
    x1 = CharField(label='occurence1', max_length=500, help_text='Ex: 4 or 6..20')
    reg2 = CharField(label='region2', max_length=500)
    x2 = CharField(label='occurence2', max_length=500, help_text='Ex: 4 or 6..20')
#     reg3 = CharField(label='region3', max_length=500)
#     x3 = CharField(label='occurence3', max_length=500, help_text='Ex: 4 or 6..20')
#     reg4 = CharField(label='region4', max_length=500)
#     x4 = CharField(label='occurence4', max_length=500, help_text='Ex: 4 or 6..20')
#     reg5 = CharField(label='region5', max_length=500)
#     x5 = CharField(label='occurence5', max_length=500, help_text='Ex: 4 or 6..20')

authoringtool/sequencelistings/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

import util
import os

from forms import SequenceListingForm, TitleForm, SequenceForm, FeatureForm, QualifierForm, EditFeatureForm

from models import SequenceListing, Title, Sequence, Feature, Qualifier
from forms import MultipleFeatureForm
from django.utils.encoding import filepath_to_uri

import logging 

logger = logging.getLogger(__name__)

class IndexView(generic.ListView):
    template_name = 'sequencelistings/index.html'
    context_object_name = 'sequencelistings'
  
    def get_queryset(self):
        """Return all sequence listings."""
        
        return SequenceListing.objects.all()

# class DetailView(generic.DetailView):
#     model = SequenceListing
#     template_name = 'sequencelistings/detail.html'

def detail(request, pk): #good
    sl = get_object_or_404(SequenceListing, pk=pk)
        
    return render(request, 'sequencelistings/detail_w3.html', {'sequencelisting': sl})

# TODO: is this needed?

def edit_sequence_data(request, pk): #good
    sl = get_object_or_404(SequenceListing, pk=pk)
        
    return render(request, 'sequencelistings/edit_sequence_data_w3.html', {'sequencelisting': sl})

@login_required 
def add_sequencelisting(request):
    if request.method == 'POST':
        form = SequenceListingForm(request.POST)
        title_form = TitleForm(request.POST)

        if form.is_valid() and title_form.is_valid():
            filingDateFromForm = request.POST.get('filingDate')
#             set to None bc the model does not handle properly empty string from form
            fd = filingDateFromForm if filingDateFromForm else None
            
            sl_instance = SequenceListing.objects.create(
            fileName = request.POST.get('fileName'),
            dtdVersion = '1',
            softwareName = 'prototype',
            softwareVersion = '0.1',
            productionDate = timezone.now(), #should be overwritten upon xml export
            
            applicantFileReference = request.POST.get('applicantFileReference'),
     
            IPOfficeCode = request.POST.get('IPOfficeCode'),
            applicationNumberText = request.POST.get('applicationNumberText'),
#             filingDate = request.POST.get('filingDate'),
            filingDate = fd,
            
            earliestPriorityIPOfficeCode = request.POST.get('earliestPriorityIPOfficeCode'),
            earliestPriorityApplicationNumberText = request.POST.get('earliestPriorityApplicationNumberText'),
            earliestPriorityFilingDate = request.POST.get('earliestPriorityFilingDate'),
         
            applicantName = request.POST.get('applicantName'),
            applicantNameLanguageCode = request.POST.get('applicantNameLanguageCode'),
            applicantNameLatin = request.POST.get('applicantNameLatin'),
         
            inventorName = request.POST.get('inventorName'),
            inventorNameLanguageCode = request.POST.get('inventorNameLanguageCode'),
            inventorNameLatin = request.POST.get('inventorNameLatin'),
            )
            
            sl_instance.save()
            
            tcd = title_form.cleaned_data
            title_instance = Title(sequenceListing = sl_instance,
                inventionTitle = tcd['inventionTitle'],
                inventionTitleLanguageCode = tcd['inventionTitleLanguageCode']
                )
            
            title_instance.save()
            
            return HttpResponseRedirect(reverse('sequencelistings:detail', 
                                                args=(sl_instance.pk,)))
    else:
        form = SequenceListingForm()
        title_form = TitleForm()
        
    return render(request, 'sequencelistings/add_sequencelisting.html', 
                  {'form': form, 'title_form': title_form})

# TODO: is this needed?

def add_title(request, pk):
    if request.method == 'POST':
        form = TitleForm(request.POST)

        if form.is_valid():
            sl = SequenceListing.objects.get(pk=pk)
            cd = form.cleaned_data
            
            title_instance = Title(sequenceListing = sl,
                inventionTitle = cd['inventionTitle'].encode('utf-8'),
                inventionTitleLanguageCode = cd['inventionTitleLanguageCode']
                )
            title_instance.save()
            
            return HttpResponseRedirect(reverse('sequencelistings:detail', args=(pk,)))
    else:
        form = TitleForm()
    return render(request, 'sequencelistings/add_title.html', {'form': form, 'pk': pk})

# TODO: is this view used actually?
def sequence(request, pk, spk):
    seq = Sequence.objects.get(pk=spk)
    form = SequenceForm(instance=seq, initial={'organism': seq.getOrganism()})
    form.organism = seq.getOrganism()
    featureFormDic = {}
    qualifierFormDic = {}
    for f in seq.feature_set.all():
        featureFormDic[f] = FeatureForm(instance=f, mt=seq.moltype, initial={'featureKey': f.featureKey})

        qualifierFormList = []
        for q in f.qualifier_set.all():
            qualifierFormList.append(QualifierForm(feature=f, 
                                                   instance=q, 
                                                   initial={'qualifierName': q.qualifierName}))

        qualifierFormDic[f] = qualifierFormList
            
    return render(request, 'sequencelistings/sequence.html', {'form': form, 'seq': seq, 
                                                              'featureFormDic': featureFormDic, 
                                                              'qualifierFormDic': qualifierFormDic,})

def add_multiple_feature(request, pk, spk):
    seq = Sequence.objects.get(pk=spk)
    if request.method == 'POST':
        form = MultipleFeatureForm(request.POST, moltype=seq.moltype)
 
        if form.is_valid():
            cd = form.cleaned_data
            
            fk = cd['featureKey']
            fl = cd['location']
            qn = cd['qualifierName']
            qv = cd['qualifierValue']
            
            if 'ra' in fl:
                locations = util.rangeFromString(fl) 
            else:
                locations = fl.split(',')
            for l in locations:
                f = Feature.objects.create(sequence=seq, featureKey=fk, location=l)
                f.save()
                q = Qualifier.objects.create(feature=f, 
                                             qualifierName = qn, 
                                             qualifierValue = qv)
                q.save()
             
            return HttpResponseRedirect(reverse('sequencelistings:edit_sequence_data', args=(seq.sequenceListing.pk,)))
    else:
        form = MultipleFeatureForm(request.POST, moltype=seq.moltype)
    return render(request, 'sequencelistings/add_multiple_feature.html', {'form': form, 'seq': seq})

def add_sequence(request, pk):
    sl = SequenceListing.objects.get(pk=pk)
    if request.method == 'POST':
        organism = request.POST.get('organism')
        form = SequenceForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            raw_residues = cd['residues']
            
            sequence_instance = Sequence(sequenceListing = sl,
                length = len(cd['residues']),
                moltype = cd['moltype'],
                residues = cd['residues'] 
                )
            
            sequence_instance.save()
            feature_source_helper(sequence_instance, organism)
#             create a note qualifier to indicate the a formula if applicable
            if '(' in raw_residues:
                value_for_note = 'note'
                if cd['moltype'] == 'AA':
                    value_for_note = 'NOTE'
                
                feature_instance = Feature.objects.filter(sequence = sequence_instance)[0]
                note_qualifier_instance = Qualifier.objects.create(feature=feature_instance, 
                                                          qualifierName=value_for_note, 
                                                          qualifierValue=raw_residues)
                note_qualifier_instance.save()
            
            return HttpResponseRedirect(reverse('sequencelistings:detail', args=(pk,)))
    else:
        form = SequenceForm()
    return render(request, 'sequencelistings/add_seq.html', {'form': form, 'pk': pk, 'seql': sl})

def feature_source_helper(seq, organism):
    '''
    Create automatically feature source for a given sequence and organism.
    '''
    value_for_source = 'source'
    value_for_organism = 'organism'
    value_for_moltype = 'mol_type'
    
    molType = seq.moltype
    
    if molType == 'AA':
        value_for_source = 'SOURCE'
        value_for_organism = 'ORGANISM'
        value_for_moltype = 'MOL_TYPE'
    
    feature_instance = Feature.objects.create(sequence=seq, 
                                              featureKey=value_for_source, 
                                              location='1..%s' % seq.length)
    feature_instance.save()
    
    organism_qualifier_instance = Qualifier.objects.create(feature=feature_instance, 
                                                  qualifierName=value_for_organism, 
                                                  qualifierValue=organism)
    organism_qualifier_instance.save()
    
    mol_type_qualifier_instance = Qualifier.objects.create(feature=feature_instance, 
                                                  qualifierName=value_for_moltype, 
                                                  qualifierValue=util.MOL_TYPE_QUALIFIER_VALUES[molType])
    mol_type_qualifier_instance.save()

authoringtool/sequencelistings/templates/sequencelistings/add_qualifier.html
<!DOCTYPE html>
{% extends 'sequencelistings/base.html' %}

{%block header_block %}
    <h2>Feature: {{feature.featureKey}} at location {{feature.location}}</h2>
    <h2>Add new qualifier</h2>
{% endblock %}

{% block body_block %}
<p><a href="{% url 'sequencelistings:index' %}">Home &gt;&gt;</a>
<a href="{% url 'sequencelistings:detail' pk %}">{{feature.sequence.sequenceListing}} &gt;&gt;</a>
<a href="{% url 'sequencelistings:sequence' pk spk %}">SEQ.ID.NO. {{feature.sequence.sequenceIdNo}} &gt;&gt;</a>

</p>
<hr>
<form action="{% url 'sequencelistings:add_qualifier' pk spk fpk %}" method="post">
    {% csrf_token %}
    <table>
        {{form.as_table }}
    </table>
    <br>
    <p><input type="submit" value="Submit" /></p>
</form>
{% endblock %}

authoringtool/sequencelistings/templates/sequencelistings/add_title.html
<!DOCTYPE html>
{% extends 'sequencelistings/base.html' %}

{%block header_block %}
    <h2>Additional title</h2>
{% endblock %}

{% block body_block %}
<form action="{% url 'sequencelistings:add_title' pk %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <br>
    <p><input type="submit" value="Submit" /></p>
</form>
{% endblock %}

authoringtool/sequencelistings/templates/sequencelistings/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load sequencelistings_extras %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">
    
    <title>st26proto - {% block title %}seql{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'sequencelistings/w3.css' %}"> -->
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">

    <link rel="stylesheet" type="text/css" href="{% static 'sequencelistings/output/resources/style.css' %}" />
    
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/sequencelistings/">Sequence listings</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'sequencelistings:index' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'sequencelistings:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'auth_logout' %}?next=/sequencelistings/">Logout</a></li>
                        
                {% else %}
                    <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                    <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
                <li><a href="{% url 'sequencelistings:about' %}">About</a></li>
                
            </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}
                {% get_sequenceListing_list sequenceListing %}
                <!-- from base sequenceListing is {{sequenceListing}} -->
                {% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                <div class="page-header">
                    {% block header_block %}{% endblock %}
                </div>
                
                {% block body_block %}{% endblock %}
                <script>
                function myFunction(id) {
                    document.getElementById(id).classList.toggle("w3-show");
                }
                </script>
                <br><br><br>
                
                <hr>
                <div id="footer">
                <p>&copy; 2016, adrian stoica</p>
                </div>
                
            </div>
        </div>
      </div>
    </div>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  
  </body>
</html>


<!-- <!DOCTYPE html>

{% load staticfiles %}
<html>
    <head>
        <title>SEQUENCE LISTING AUTHORING TOOL PROTOTYPE</title>
        
        <link rel="stylesheet" type="text/css" href="{% static 'sequencelistings/style.css' %}" />
    </head> 
    <body> 
        <h1 id="prototypeheader">SEQUENCE LISTING AUTHORING TOOL PROTOTYPE</h1>  
        {% block content %}
        {% endblock %}
    </body>
</html> -->

authoringtool/sequencelistings/templates/sequencelistings/delete_sequence.html
<!DOCTYPE html>

{% extends 'sequencelistings/base.html' %}
{% load my_filters %}

{%block header_block %}
    <h2><strong>DELETE</strong>SEQ.ID.NO. {{seq.sequenceIdNo}}?????</h2>
{% endblock %}

{% block body_block %}
<p><a href="{% url 'sequencelistings:index' %}">Home &gt;&gt;</a>
<a href="{% url 'sequencelistings:detail' seq.sequenceListing.pk %}">{{seq.sequenceListing}} &gt;&gt;</a>
</p>

<hr>

<form action="" method="post">
    {% csrf_token %}
    <!-- <table>
        {{ form.as_table }}
    </table> -->
    <!-- <hr>
    <h2>Feature table</h2>
    <hr>
    
    {% for f, ff in featureFormDic.iteritems %}
        <table>
            {{ff.as_table}}
        </table>
        <br>
        <ul>
        {% for qf in qualifierFormDic|access:f %}
            <li><p>{{qf}}</p></li>
        {% endfor %}
        </ul>
        <p>
        <a href='/sequencelistings/sl{{seq.sequenceListing.pk}}/seq{{seq.pk}}/f{{f.pk}}/add_qualifier/'><span  class="addQalifierLink">Add new qualifier</span></a>
        </p>
        <hr>
        
    {% endfor %}
    <p>
    <a href='/sequencelistings/sl{{seq.sequenceListing.pk}}/seq{{seq.pk}}/add_feature/'><span  class="addFeatureLink">Add new feature</span></a>
    </p> -->
    <!-- <br>
    <p>
    <a href="{% url 'sequencelistings:add_multiple_feature' seq.sequenceListing.pk seq.pk %}"><span  class="addFeatureLink">Add multiple feature</span></a>

    </p>
    <br> -->
    <!-- <table class="featuretable">
        <tr>
            <th>feature key</th>
            <th>location</th>
            <th>qualifiers</th>
        </tr>
        {% for f in seq.feature_set.all %}
            <tr>
                <td>
                    {{f.featureKey}}
                </td>
                <td>{{f.location}}</td>
                <td>                          
                    <table class="qualifiertable">
                        <tr>
                            <th>name</th>
                            <th>value</th>
                        </tr>
                        {% if f.qualifier_set.all %}
                            {% for q in f.qualifier_set.all %}
                            <tr>
                                <td>{{q.qualifierName}}</td>
                                <td>{{q.qualifierValue}}</td>
                            </tr>
                            {% endfor %}
                        {% endif %}
                        <tr>
                            <td class="addQalifierLink" colspan="2">
                            <a href='/sequencelistings/sl{{seq.sequenceListing.pk}}/seq{{seq.pk}}/f{{f.pk}}/add_qualifier/'>Add new qualifier</a>
                            </td>
                        </tr>
                    </table>                         
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td class="addFeatureLink" colspan="2">
                <a href='/sequencelistings/sl{{seq.sequenceListing.pk}}/seq{{seq.pk}}/add_feature/'>Add new feature</a>
            </td>
        </tr>
        <tr>
            <td class="addFeatureLink" colspan="2">
                <a href='/sequencelistings/sl{{seq.sequenceListing.pk}}/seq{{seq.pk}}/add_multiple_feature/'>Add multiple feature</a>
            </td>
        </tr>                   
    </table> -->
    <p>
        <input type="submit" value="Delete" />
    </p>
</form>
{% endblock %}

authoringtool/sequencelistings/templates/sequencelistings/index.html
<!DOCTYPE html>
{% extends 'sequencelistings/base.html' %}

{% block title%}Index{% endblock %}

{%block header_block %}
    <h2>WELCOME 
        {% if user.is_authenticated %}
            {{user.username}}!
        {% endif %}
    </h2>
{% endblock %}

{% block body_block %}

    <p>This website is a proof of concept on how to generate a sequence listing in XML format.
    It is a prototype (so limited functionality!) built only for information and demonstration purposes. 
    </p>
    
    <p>The prototype enables the user to:</p>
    <ol>
        <li>Create a sequence listing by filling in a number of forms, i.e. 
            <ul>
                <li>general information form</li>
                <li>sequence data forms (create sequence, feature, qualifier)</li>
            </ul>
        </li>
        <li>Observe the constraints imposed by controlled vocabularies and alphabets</li>
        <li>Store and display previously created sequence listings</li>
        <li>Generate the sequence listing as XML file</li>
        <li>Display in the browser the generated XML file</li>
        <li>Download to the local disc the generated XML file</li>
            
    </ol>
    <hr>
    <h2>SEQUENCE LISTING PORTOFOLIO</h2>
    <p>Navigate to previously created sequence listings by following the link in the column 'file name'.</p>
    <p>Registered users can create sequence listings or add sequences to previously created sequence listings.</p> 
        
    {% if not user.is_authenticated %}
        <p>Follow this link for <a href="{% url 'registration_register' %}">registration</a>.
    {% endif %}
    <h3>Note</h3>
    <p>The sequence listing 'Invention_SEQL' is not editable (it is a specimen).</p>
    </p>
    {% if sequencelistings %}
        <table id="home_page_table">
            <tr>
                <th>file name</th>
                <th>invention title</th>
                <th>number of sequences</th>
            </tr>
            {% for sl in sequencelistings %}
                <tr>
                    <td><a href="{% url 'sequencelistings:detail' sl.id %}">{{ sl.fileName }}</a></td>
                    <td>{{sl.getFirstTitle}}</td>
                    <td>{{sl.sequenceTotalQuantity}}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p id="no_seqls_par">No sequence listings are available.</p>
    {% endif %}
    {% if user.is_authenticated %}
        <h2>SEQUENCE LISTING GENERATOR</h2>
        <p>This section enables you to create a new sequence listing.</p>
        <a id="add_seql_link" href="{% url 'sequencelistings:add_sequencelisting' %}">Add new sequence listing</a>
    {% endif %}
    <hr>
    <h3>Disclaimer</h3>
    <p>This website has been built <strong>only for information purposes</strong>.</p>
    <p>No rights can be derived from visiting, registering and/or exploring the functionality of this website.</p>
    <p><a href="{% url 'sequencelistings:about' %}">More on About page</a></p>
{% endblock %}